"""Sample initial data for table initialization.

Fun range optimizer demo data for:
- Craft Beer & Hard Seltzer (15 products)
- Hot Sauce Collection (15 products)
- Premium Ice Cream (15 products)

Total: 45 products across 3 categories
Designed for: Min SKUs 10, Max SKUs 15, Max Brand Share 30%
"""

INITIAL_DATA = [
    # ==========================================================================
    # CRAFT BEER & HARD SELTZER (15 products)
    # ==========================================================================
    {"SKU_ID": "SKU3001", "SKU_NAME": "Stone & Wood Pacific Ale 6pk", "BRAND": "Stone & Wood", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Craft Beer", "PACK_SIZE": "6x330ml", "PACK_WIDTH_MM": 180, "WEEKLY_UNITS": 85, "UNIT_PRICE": 24.00, "UNIT_COST": 14.40, "GROSS_MARGIN_PCT": 40, "CURRENT_FACINGS": 3, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU3002", "SKU_NAME": "Stone & Wood Green Coast Lager 6pk", "BRAND": "Stone & Wood", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Craft Beer", "PACK_SIZE": "6x330ml", "PACK_WIDTH_MM": 180, "WEEKLY_UNITS": 65, "UNIT_PRICE": 23.00, "UNIT_COST": 13.80, "GROSS_MARGIN_PCT": 40, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU3003", "SKU_NAME": "Balter XPA 4pk", "BRAND": "Balter", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Craft Beer", "PACK_SIZE": "4x375ml", "PACK_WIDTH_MM": 150, "WEEKLY_UNITS": 95, "UNIT_PRICE": 22.00, "UNIT_COST": 13.20, "GROSS_MARGIN_PCT": 40, "CURRENT_FACINGS": 3, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU3004", "SKU_NAME": "Balter Captain Sensible 4pk", "BRAND": "Balter", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Craft Beer", "PACK_SIZE": "4x375ml", "PACK_WIDTH_MM": 150, "WEEKLY_UNITS": 55, "UNIT_PRICE": 20.00, "UNIT_COST": 12.00, "GROSS_MARGIN_PCT": 40, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU3005", "SKU_NAME": "Young Henrys Newtowner 6pk", "BRAND": "Young Henrys", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Craft Beer", "PACK_SIZE": "6x330ml", "PACK_WIDTH_MM": 180, "WEEKLY_UNITS": 70, "UNIT_PRICE": 23.50, "UNIT_COST": 14.10, "GROSS_MARGIN_PCT": 40, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU3006", "SKU_NAME": "Young Henrys Stayer 6pk", "BRAND": "Young Henrys", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Craft Beer", "PACK_SIZE": "6x330ml", "PACK_WIDTH_MM": 180, "WEEKLY_UNITS": 45, "UNIT_PRICE": 22.00, "UNIT_COST": 13.20, "GROSS_MARGIN_PCT": 40, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU3007", "SKU_NAME": "4 Pines Pale Ale 6pk", "BRAND": "4 Pines", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Craft Beer", "PACK_SIZE": "6x330ml", "PACK_WIDTH_MM": 180, "WEEKLY_UNITS": 75, "UNIT_PRICE": 22.50, "UNIT_COST": 13.50, "GROSS_MARGIN_PCT": 40, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU3008", "SKU_NAME": "Pirate Life South Coast Pale 6pk", "BRAND": "Pirate Life", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Craft Beer", "PACK_SIZE": "6x355ml", "PACK_WIDTH_MM": 185, "WEEKLY_UNITS": 60, "UNIT_PRICE": 25.00, "UNIT_COST": 15.00, "GROSS_MARGIN_PCT": 40, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU3009", "SKU_NAME": "White Claw Variety 12pk", "BRAND": "White Claw", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Hard Seltzer", "PACK_SIZE": "12x330ml", "PACK_WIDTH_MM": 260, "WEEKLY_UNITS": 120, "UNIT_PRICE": 32.00, "UNIT_COST": 17.60, "GROSS_MARGIN_PCT": 45, "CURRENT_FACINGS": 4, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU3010", "SKU_NAME": "White Claw Mango 4pk", "BRAND": "White Claw", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Hard Seltzer", "PACK_SIZE": "4x330ml", "PACK_WIDTH_MM": 130, "WEEKLY_UNITS": 80, "UNIT_PRICE": 18.00, "UNIT_COST": 9.90, "GROSS_MARGIN_PCT": 45, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU3011", "SKU_NAME": "Fellr Watermelon Seltzer 4pk", "BRAND": "Fellr", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Hard Seltzer", "PACK_SIZE": "4x330ml", "PACK_WIDTH_MM": 130, "WEEKLY_UNITS": 55, "UNIT_PRICE": 19.00, "UNIT_COST": 10.45, "GROSS_MARGIN_PCT": 45, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "new"},
    {"SKU_ID": "SKU3012", "SKU_NAME": "Fellr Lime & Soda 4pk", "BRAND": "Fellr", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Hard Seltzer", "PACK_SIZE": "4x330ml", "PACK_WIDTH_MM": 130, "WEEKLY_UNITS": 50, "UNIT_PRICE": 19.00, "UNIT_COST": 10.45, "GROSS_MARGIN_PCT": 45, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU3013", "SKU_NAME": "Brookvale Union Ginger Beer 4pk", "BRAND": "Brookvale Union", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Hard Seltzer", "PACK_SIZE": "4x330ml", "PACK_WIDTH_MM": 130, "WEEKLY_UNITS": 65, "UNIT_PRICE": 20.00, "UNIT_COST": 11.00, "GROSS_MARGIN_PCT": 45, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU3014", "SKU_NAME": "Brookvale Union Vodka Lemon 4pk", "BRAND": "Brookvale Union", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Hard Seltzer", "PACK_SIZE": "4x330ml", "PACK_WIDTH_MM": 130, "WEEKLY_UNITS": 45, "UNIT_PRICE": 20.00, "UNIT_COST": 11.00, "GROSS_MARGIN_PCT": 45, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU3015", "SKU_NAME": "Good Tides Passionfruit 4pk", "BRAND": "Good Tides", "CATEGORY": "Beer & Seltzer", "SEGMENT": "Hard Seltzer", "PACK_SIZE": "4x330ml", "PACK_WIDTH_MM": 130, "WEEKLY_UNITS": 35, "UNIT_PRICE": 17.00, "UNIT_COST": 9.35, "GROSS_MARGIN_PCT": 45, "CURRENT_FACINGS": 1, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "new"},

    # ==========================================================================
    # HOT SAUCE COLLECTION (15 products)
    # ==========================================================================
    {"SKU_ID": "SKU4001", "SKU_NAME": "Sriracha Original 455ml", "BRAND": "Sriracha", "CATEGORY": "Hot Sauce", "SEGMENT": "Asian Style", "PACK_SIZE": "455ml", "PACK_WIDTH_MM": 80, "WEEKLY_UNITS": 145, "UNIT_PRICE": 6.50, "UNIT_COST": 2.93, "GROSS_MARGIN_PCT": 55, "CURRENT_FACINGS": 4, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU4002", "SKU_NAME": "Sriracha Garlic 255ml", "BRAND": "Sriracha", "CATEGORY": "Hot Sauce", "SEGMENT": "Asian Style", "PACK_SIZE": "255ml", "PACK_WIDTH_MM": 65, "WEEKLY_UNITS": 75, "UNIT_PRICE": 5.00, "UNIT_COST": 2.25, "GROSS_MARGIN_PCT": 55, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU4003", "SKU_NAME": "Tabasco Original 150ml", "BRAND": "Tabasco", "CATEGORY": "Hot Sauce", "SEGMENT": "Louisiana Style", "PACK_SIZE": "150ml", "PACK_WIDTH_MM": 50, "WEEKLY_UNITS": 110, "UNIT_PRICE": 5.00, "UNIT_COST": 2.25, "GROSS_MARGIN_PCT": 55, "CURRENT_FACINGS": 3, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU4004", "SKU_NAME": "Tabasco Chipotle 150ml", "BRAND": "Tabasco", "CATEGORY": "Hot Sauce", "SEGMENT": "Louisiana Style", "PACK_SIZE": "150ml", "PACK_WIDTH_MM": 50, "WEEKLY_UNITS": 65, "UNIT_PRICE": 5.50, "UNIT_COST": 2.48, "GROSS_MARGIN_PCT": 55, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU4005", "SKU_NAME": "Cholula Original 150ml", "BRAND": "Cholula", "CATEGORY": "Hot Sauce", "SEGMENT": "Mexican Style", "PACK_SIZE": "150ml", "PACK_WIDTH_MM": 55, "WEEKLY_UNITS": 95, "UNIT_PRICE": 5.50, "UNIT_COST": 2.75, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 3, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU4006", "SKU_NAME": "Cholula Green Pepper 150ml", "BRAND": "Cholula", "CATEGORY": "Hot Sauce", "SEGMENT": "Mexican Style", "PACK_SIZE": "150ml", "PACK_WIDTH_MM": 55, "WEEKLY_UNITS": 55, "UNIT_PRICE": 5.50, "UNIT_COST": 2.75, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU4007", "SKU_NAME": "Frank's RedHot Original 354ml", "BRAND": "Frank's", "CATEGORY": "Hot Sauce", "SEGMENT": "Louisiana Style", "PACK_SIZE": "354ml", "PACK_WIDTH_MM": 70, "WEEKLY_UNITS": 85, "UNIT_PRICE": 6.00, "UNIT_COST": 2.70, "GROSS_MARGIN_PCT": 55, "CURRENT_FACINGS": 3, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU4008", "SKU_NAME": "Frank's Buffalo Wings 354ml", "BRAND": "Frank's", "CATEGORY": "Hot Sauce", "SEGMENT": "Louisiana Style", "PACK_SIZE": "354ml", "PACK_WIDTH_MM": 70, "WEEKLY_UNITS": 70, "UNIT_PRICE": 6.50, "UNIT_COST": 2.93, "GROSS_MARGIN_PCT": 55, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU4009", "SKU_NAME": "Valentina Salsa Picante 370ml", "BRAND": "Valentina", "CATEGORY": "Hot Sauce", "SEGMENT": "Mexican Style", "PACK_SIZE": "370ml", "PACK_WIDTH_MM": 65, "WEEKLY_UNITS": 60, "UNIT_PRICE": 3.50, "UNIT_COST": 1.58, "GROSS_MARGIN_PCT": 55, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU4010", "SKU_NAME": "Sambal Oelek Chili Paste 226g", "BRAND": "Huy Fong", "CATEGORY": "Hot Sauce", "SEGMENT": "Asian Style", "PACK_SIZE": "226g", "PACK_WIDTH_MM": 75, "WEEKLY_UNITS": 80, "UNIT_PRICE": 4.50, "UNIT_COST": 2.03, "GROSS_MARGIN_PCT": 55, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU4011", "SKU_NAME": "Da Bomb Beyond Insanity 118ml", "BRAND": "Da Bomb", "CATEGORY": "Hot Sauce", "SEGMENT": "Extreme Heat", "PACK_SIZE": "118ml", "PACK_WIDTH_MM": 45, "WEEKLY_UNITS": 25, "UNIT_PRICE": 15.00, "UNIT_COST": 7.50, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 1, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU4012", "SKU_NAME": "Bunsters Black Label 236ml", "BRAND": "Bunsters", "CATEGORY": "Hot Sauce", "SEGMENT": "Craft/Artisan", "PACK_SIZE": "236ml", "PACK_WIDTH_MM": 60, "WEEKLY_UNITS": 45, "UNIT_PRICE": 12.00, "UNIT_COST": 6.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "new"},
    {"SKU_ID": "SKU4013", "SKU_NAME": "Bunsters Shit the Bed 236ml", "BRAND": "Bunsters", "CATEGORY": "Hot Sauce", "SEGMENT": "Extreme Heat", "PACK_SIZE": "236ml", "PACK_WIDTH_MM": 60, "WEEKLY_UNITS": 30, "UNIT_PRICE": 14.00, "UNIT_COST": 7.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 1, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU4014", "SKU_NAME": "El Yucateco Green Habanero 120ml", "BRAND": "El Yucateco", "CATEGORY": "Hot Sauce", "SEGMENT": "Mexican Style", "PACK_SIZE": "120ml", "PACK_WIDTH_MM": 45, "WEEKLY_UNITS": 40, "UNIT_PRICE": 4.00, "UNIT_COST": 1.80, "GROSS_MARGIN_PCT": 55, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU4015", "SKU_NAME": "Secret Aardvark Habanero 236ml", "BRAND": "Secret Aardvark", "CATEGORY": "Hot Sauce", "SEGMENT": "Craft/Artisan", "PACK_SIZE": "236ml", "PACK_WIDTH_MM": 60, "WEEKLY_UNITS": 35, "UNIT_PRICE": 10.00, "UNIT_COST": 5.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 1, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "new"},

    # ==========================================================================
    # PREMIUM ICE CREAM (15 products)
    # ==========================================================================
    {"SKU_ID": "SKU5001", "SKU_NAME": "Ben & Jerry's Cookie Dough 458ml", "BRAND": "Ben & Jerry's", "CATEGORY": "Ice Cream", "SEGMENT": "Premium Pints", "PACK_SIZE": "458ml", "PACK_WIDTH_MM": 110, "WEEKLY_UNITS": 90, "UNIT_PRICE": 13.50, "UNIT_COST": 6.75, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 3, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU5002", "SKU_NAME": "Ben & Jerry's Phish Food 458ml", "BRAND": "Ben & Jerry's", "CATEGORY": "Ice Cream", "SEGMENT": "Premium Pints", "PACK_SIZE": "458ml", "PACK_WIDTH_MM": 110, "WEEKLY_UNITS": 75, "UNIT_PRICE": 13.50, "UNIT_COST": 6.75, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU5003", "SKU_NAME": "Ben & Jerry's Half Baked 458ml", "BRAND": "Ben & Jerry's", "CATEGORY": "Ice Cream", "SEGMENT": "Premium Pints", "PACK_SIZE": "458ml", "PACK_WIDTH_MM": 110, "WEEKLY_UNITS": 85, "UNIT_PRICE": 13.50, "UNIT_COST": 6.75, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 3, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU5004", "SKU_NAME": "Häagen-Dazs Salted Caramel 457ml", "BRAND": "Häagen-Dazs", "CATEGORY": "Ice Cream", "SEGMENT": "Premium Pints", "PACK_SIZE": "457ml", "PACK_WIDTH_MM": 110, "WEEKLY_UNITS": 70, "UNIT_PRICE": 14.00, "UNIT_COST": 7.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU5005", "SKU_NAME": "Häagen-Dazs Belgian Chocolate 457ml", "BRAND": "Häagen-Dazs", "CATEGORY": "Ice Cream", "SEGMENT": "Premium Pints", "PACK_SIZE": "457ml", "PACK_WIDTH_MM": 110, "WEEKLY_UNITS": 65, "UNIT_PRICE": 14.00, "UNIT_COST": 7.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU5006", "SKU_NAME": "Häagen-Dazs Vanilla 457ml", "BRAND": "Häagen-Dazs", "CATEGORY": "Ice Cream", "SEGMENT": "Premium Pints", "PACK_SIZE": "457ml", "PACK_WIDTH_MM": 110, "WEEKLY_UNITS": 80, "UNIT_PRICE": 14.00, "UNIT_COST": 7.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU5007", "SKU_NAME": "Connoisseur Murray River Salted Caramel 1L", "BRAND": "Connoisseur", "CATEGORY": "Ice Cream", "SEGMENT": "Premium Tubs", "PACK_SIZE": "1L", "PACK_WIDTH_MM": 140, "WEEKLY_UNITS": 55, "UNIT_PRICE": 12.00, "UNIT_COST": 6.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU5008", "SKU_NAME": "Connoisseur Cookies & Cream 1L", "BRAND": "Connoisseur", "CATEGORY": "Ice Cream", "SEGMENT": "Premium Tubs", "PACK_SIZE": "1L", "PACK_WIDTH_MM": 140, "WEEKLY_UNITS": 50, "UNIT_PRICE": 12.00, "UNIT_COST": 6.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU5009", "SKU_NAME": "Halo Top Birthday Cake 473ml", "BRAND": "Halo Top", "CATEGORY": "Ice Cream", "SEGMENT": "Low-Cal", "PACK_SIZE": "473ml", "PACK_WIDTH_MM": 100, "WEEKLY_UNITS": 45, "UNIT_PRICE": 11.00, "UNIT_COST": 5.50, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU5010", "SKU_NAME": "Halo Top Chocolate 473ml", "BRAND": "Halo Top", "CATEGORY": "Ice Cream", "SEGMENT": "Low-Cal", "PACK_SIZE": "473ml", "PACK_WIDTH_MM": 100, "WEEKLY_UNITS": 40, "UNIT_PRICE": 11.00, "UNIT_COST": 5.50, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU5011", "SKU_NAME": "Magnum Double Caramel 4pk", "BRAND": "Magnum", "CATEGORY": "Ice Cream", "SEGMENT": "Sticks", "PACK_SIZE": "4x86ml", "PACK_WIDTH_MM": 120, "WEEKLY_UNITS": 60, "UNIT_PRICE": 10.00, "UNIT_COST": 5.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU5012", "SKU_NAME": "Magnum Classic 4pk", "BRAND": "Magnum", "CATEGORY": "Ice Cream", "SEGMENT": "Sticks", "PACK_SIZE": "4x86ml", "PACK_WIDTH_MM": 120, "WEEKLY_UNITS": 70, "UNIT_PRICE": 10.00, "UNIT_COST": 5.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU5013", "SKU_NAME": "Bulla Creamy Classics Vanilla 2L", "BRAND": "Bulla", "CATEGORY": "Ice Cream", "SEGMENT": "Family Tubs", "PACK_SIZE": "2L", "PACK_WIDTH_MM": 180, "WEEKLY_UNITS": 85, "UNIT_PRICE": 8.00, "UNIT_COST": 4.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 3, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": True, "STATUS": "active"},
    {"SKU_ID": "SKU5014", "SKU_NAME": "Bulla Creamy Classics Chocolate 2L", "BRAND": "Bulla", "CATEGORY": "Ice Cream", "SEGMENT": "Family Tubs", "PACK_SIZE": "2L", "PACK_WIDTH_MM": 180, "WEEKLY_UNITS": 75, "UNIT_PRICE": 8.00, "UNIT_COST": 4.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 2, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "active"},
    {"SKU_ID": "SKU5015", "SKU_NAME": "Gelato Messina Salted Caramel 500ml", "BRAND": "Gelato Messina", "CATEGORY": "Ice Cream", "SEGMENT": "Premium Pints", "PACK_SIZE": "500ml", "PACK_WIDTH_MM": 110, "WEEKLY_UNITS": 35, "UNIT_PRICE": 16.00, "UNIT_COST": 8.00, "GROSS_MARGIN_PCT": 50, "CURRENT_FACINGS": 1, "IS_PRIVATE_LABEL": False, "IS_MUST_STOCK": False, "STATUS": "new"},
]

# ==========================================================================
# Demo Optimization Results
# ==========================================================================
OPTIMIZATION_RESULTS = [
    {"SKU_ID": "SKU3001", "SKU_NAME": "Stone & Wood Pacific Ale 6pk", "CATEGORY": "Beer & Seltzer", "BRAND": "Stone & Wood", "WEEKLY_UNITS": 85, "UNIT_PRICE": 24.00, "UNIT_COST": 14.40, "OPTIMAL_ORDER_QTY": 95, "SAFETY_STOCK": 45, "MAX_STOCK_LEVEL": 140, "REORDER_POINT": 65, "TOTAL_ANNUAL_COST": 6800.00, "EXPECTED_ANNUAL_REVENUE": 10608.00, "EXPECTED_ANNUAL_PROFIT": 3808.00, "TURNOVER_RATE": 12.5, "SERVICE_LEVEL": 0.95, "OPTIMIZATION_STATUS": "optimal"},
    {"SKU_ID": "SKU3003", "SKU_NAME": "Balter XPA 4pk", "CATEGORY": "Beer & Seltzer", "BRAND": "Balter", "WEEKLY_UNITS": 95, "UNIT_PRICE": 22.00, "UNIT_COST": 13.20, "OPTIMAL_ORDER_QTY": 105, "SAFETY_STOCK": 50, "MAX_STOCK_LEVEL": 155, "REORDER_POINT": 75, "TOTAL_ANNUAL_COST": 7500.00, "EXPECTED_ANNUAL_REVENUE": 10890.00, "EXPECTED_ANNUAL_PROFIT": 3390.00, "TURNOVER_RATE": 13.2, "SERVICE_LEVEL": 0.95, "OPTIMIZATION_STATUS": "optimal"},
    {"SKU_ID": "SKU3009", "SKU_NAME": "White Claw Variety 12pk", "CATEGORY": "Beer & Seltzer", "BRAND": "White Claw", "WEEKLY_UNITS": 120, "UNIT_PRICE": 32.00, "UNIT_COST": 17.60, "OPTIMAL_ORDER_QTY": 135, "SAFETY_STOCK": 65, "MAX_STOCK_LEVEL": 200, "REORDER_POINT": 95, "TOTAL_ANNUAL_COST": 9200.00, "EXPECTED_ANNUAL_REVENUE": 19968.00, "EXPECTED_ANNUAL_PROFIT": 10768.00, "TURNOVER_RATE": 15.8, "SERVICE_LEVEL": 0.95, "OPTIMIZATION_STATUS": "optimal"},
]
